bdusses = [
            #wanwufusu037
            "0NyTW5EODJoZHpBS3p3LXlpTG1OdjVRREZKYzNaME1QOWF2bDFEY0FLZ2lSU0ZkSUFBQUFBJCQAAAAAAAAAAAEAAAAkj9T0d2Fud3VmdXN1MDM3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACK4-VwiuPlcV",
            #sfdiuss88
            "lVlN3p5NDdmaEliRzBROHFQdlZMU3Aza1ZFZWJ5NFlFam5FbEhrU290N2ZCaHRkSVFBQUFBJCQAAAAAAAAAAAEAAABk9k71c2ZkaXVzczg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN9581zfefNcW",
        ]

