bdusses = [
            "",
            "FM0MG9QUWktMzMyUVpscFp4ZEY3LVliOUkzbEZGZXdiYmZNak9pOVU3blhNeGRkRVFBQUFBJCQAAAAAAAAAAAEAAAC-YTb1uPHO78uutc4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANem71zXpu9cM",
        ]
reply_bduss = "1JNVlM2RUYtaTBlRDgxUGNXNWZNWkJjS2l4c2E4MEx0OGVkWW1uc1Y2UGFOeGRkRVFBQUFBJCQAAAAAAAAAAAEAAADg0xv0uPHO79HQvr8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANqq71zaqu9cT"