bdusses = [
            #wanwufusu037
            "1lhflVUZFVUNGtSSTlKV3l6b3NWQmluYW5QeEV4Y2N0TUNQQm5-ZXh4R09laUJkSUFBQUFBJCQAAAAAAAAAAAEAAAAkj9T0d2Fud3VmdXN1MDM3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI7t-FyO7fhca",
            #sfdiuss88
            "lVlN3p5NDdmaEliRzBROHFQdlZMU3Aza1ZFZWJ5NFlFam5FbEhrU290N2ZCaHRkSVFBQUFBJCQAAAAAAAAAAAEAAABk9k71c2ZkaXVzczg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN9581zfefNcW",
        ]

